"""adding dummy field to check migration is working or not

Revision ID: 0601534c966e
Revises: 6fab02987574
Create Date: 2024-09-04 05:06:47.108485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0601534c966e'
down_revision = '6fab02987574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy_field', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('dummy_field')

    # ### end Alembic commands ###
