"""extends SQLALCHEMY functionaly for both admin and base_model

Revision ID: 0cf2ffb04dc2
Revises: 0601534c966e
Create Date: 2024-09-04 05:40:53.065320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0cf2ffb04dc2'
down_revision = '0601534c966e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the foreign key constraint before dropping tables
    op.drop_constraint('employees_ibfk_1', 'employees', type_='foreignkey')
    
    # Now drop the tables
    op.drop_table('employees')
    
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index('key')

    op.drop_table('settings')
    op.drop_table('admins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
        sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
        sa.Column('email', mysql.VARCHAR(length=128), nullable=False),
        sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('phone', mysql.VARCHAR(length=128), nullable=False),
        sa.Column('department', mysql.VARCHAR(length=128), nullable=False),
        sa.Column('start_date', mysql.DATETIME(), nullable=False),
        sa.Column('salary', mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('role', mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('photo', mysql.VARCHAR(length=250), nullable=True),
        sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
        sa.Column('admin_id', mysql.VARCHAR(length=60), nullable=True),
        sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
        sa.Column('created_at', mysql.DATETIME(), nullable=False),
        sa.Column('updated_at', mysql.DATETIME(), nullable=False),
        sa.Column('dummy_field', mysql.VARCHAR(length=50), nullable=True),
        sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name='employees_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    
    op.create_table('settings',
        sa.Column('key', mysql.VARCHAR(length=128), nullable=False),
        sa.Column('value', mysql.VARCHAR(length=128), nullable=False),
        sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
        sa.Column('created_at', mysql.DATETIME(), nullable=False),
        sa.Column('updated_at', mysql.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index('key', ['key'], unique=True)

    op.create_table('admins',
        sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
        sa.Column('email', mysql.VARCHAR(length=128), nullable=False),
        sa.Column('password', mysql.VARCHAR(length=256), nullable=False),
        sa.Column('role', mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
        sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
        sa.Column('created_at', mysql.DATETIME(), nullable=False),
        sa.Column('updated_at', mysql.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
