"""edit admin id to be nullable and salary to be intger

Revision ID: e8b01b84f622
Revises: e15b34f77b12
Create Date: 2024-08-29 05:17:14.650471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8b01b84f622'
down_revision = 'e15b34f77b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('users')
    op.drop_table('roles')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('salary',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('admin_id',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('salary',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)

    op.create_table('roles',
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=260), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('email', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('role_id', mysql.VARCHAR(length=128), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='users_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
